const main = async () => {
	//
};

main().catch((err) => {
	console.error(err);
	process.exitCode = 1;
});
